name: test
description: test package for js
dependencies:
  unittest: any
  js:
    path: ../../
transformers:
- js
- js/initializer
- $dart2js:
#    checked: true
    commandLineOptions: ['--dump-info']
