name: js
version: 0.0.23
authors:
- Dart Team <misc@dartlang.org>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/js-interop
environment:
  sdk: '>=0.4.1+0.r19425'
dependencies:
  meta: any
  browser: any
dev_dependencies:
  unittest: any
