name: js
version: 0.2.1
authors:
- Dart Team <misc@dartlang.org>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/js-interop
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
dev_dependencies:
  ghpages_generator: '>=0.0.1 <0.1.0'
  unittest: '>=0.9.0 <0.10.0'
